server:
  port: 9001

spring:
  application:
    name: product-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/multi_tenant_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/realms/MultiTenantSaaS
          jwk-set-uri: http://nexus-auth:8080/realms/MultiTenantSaaS/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  show-actuator: true
